version = 0.1

[default.deploy.parameters]
stack_name = "fantasy-baseball-api"
resolve_s3 = true
s3_prefix = "fantasy-baseball-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
